### ISSUE TITLE
Git/Github usage recomendations

### ISSUE THREAD

**Issue by tshemsedinov** [HowProgrammingWorks/VersionControl#1]
Please find guides, videos, articles and docs for students

**Comment by tshemsedinov** [comment]
We need basics but we need it ASAP. Maybe it's easier to find a short video or single page guide. What we need: how to install and configure, clone, pull, commit, push.

**Comment by aqrln** [comment]
Okay, got it. I'll bump its priority in my todo-list :)

**Comment by aqrln** [comment]
Closed via 40e1fcc, 77aad84, 0e3dbdd, 5675b9f and 6cb3ebb.
