### ISSUE TITLE
Update the description of the repository

### ISSUE THREAD

**Issue by aqrln** [HowProgrammingWorks/VersionControl#2]
Current description which says

> GIT and GitHub Version Control Systems Usage Recomendations

has following issues:

* GIT is not an official spelling of Git,
* GitHub is not a version control system,
* the word 'recom**m**endations' has a spelling mistake.

I propose to reword it like this:

> Git and GitHub Usage Recommendations

or this:

> Git Version Control System and GitHub Usage Recommendations

or even this:

> Git and GitHub Links, Tutorials and Usage Recommendations

**Comment by tshemsedinov** [comment]
I'd prefer `Git Version Control System and GitHub Usage Recommendations`
Thanks!
